### PR TITLE
charts/turbinia Add version_check turbinia runtime configurable parameter.

### PR DESCRIPTION
**Pull request by hacktobeer**
### Description of the change

The Turbinia configuration has a parameter to set runtime version checking between server and worker (VERSION_CHECK). This PR adds the option to set this in the helm chart (versioncheck.enabled). It defaults to True.

### Checklist

- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [x] Variables are documented in the values.yaml and added to the `README.md` using[readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [x] Title of the pull request follows this pattern [charts/<name_of_the_chart>] Descriptive title

### CODE REVIEW

**Comment by hacktobeer** [comment]
Will run the readme generator next week.

**Comment by hacktobeer** [comment]
readme generated, @wajihyassine ptal

**Review by wajihyassine — APPROVED** [review]
LGTM! Will merge once we get the GH actions PR merged so we can test it works

**Comment by hacktobeer** [comment]
@wajihyassine  ran action and passes, feel free to merge.

**Pull request merged**
